export const PORT = 3000
export const MAX_BOOT_WAIT_MS = 20000
export const POLL_INTERVAL_MS = 500
export const BACKEND_URL = process.env.BACKEND_URL ?? `http://localhost:3000`
export const REDIS_HOST = process.env.REDIS_HOST ?? "redis"
export const REDIS_PORT = Number(process.env.REDIS_PORT ?? 6379)
export const MAIN_AGENT_MAX_ITERATIONS = 30
export const MAX_SUBAGENT_ITERATIONS = 20
export const MAX_CONTEXT_WINDOW_LENGTH = 2_00_000
export const COMPACTION_PARAMETER = 10
export const COMPACT_THRESHOLD = 0.8*MAX_CONTEXT_WINDOW_LENGTH
export const DEBUGGERR_MAX_ITERATIONS = 10
export const CODER_MAX_ITERATIONS = 10