export const PORT = 3000
export const SANDBOX_HOME = '/home/user'
export const PROJECT_ROOT = `${SANDBOX_HOME}/app`
export const MAX_BOOT_WAIT_MS = 20000
export const POLL_INTERVAL_MS = 500
export const BACKEND_URL = process.env.BACKEND_URL ?? `http://localhost:3000`
export const REDIS_HOST = process.env.REDIS_HOST ?? "redis"
export const REDIS_PORT = Number(process.env.REDIS_PORT ?? 6379)
export const MAIN_AGENT_MAX_ITERATIONS = 30
export const MAX_CONTEXT_WINDOW_LENGTH = 2_00_000
export const COMPACTION_PARAMETER = 10
export const COMPACT_THRESHOLD = 0.8*MAX_CONTEXT_WINDOW_LENGTH
export const CODER_MAX_ITERATIONS = 10
export const DEBUGGERR_MAX_ITERATIONS = 10
export const RESEARCHER_MAX_ITERATIONS = 10
export const TESTER_MAX_ITERATIONS = 5
export const UI_EXPERT_MAX_ITERATIONS = 5
export const TESTER_DEBUGGER_LOOP_MAX_ITERATIONS = 10