export const PORT = 3000
export const SANDBOX_HOME = '/home/user'
export const PROJECT_ROOT = `${SANDBOX_HOME}/app`
export const MAX_BOOT_WAIT_MS = 20000
export const POLL_INTERVAL_MS = 500
export const BACKEND_URL = process.env.BACKEND_URL ?? `http://localhost:3000`
export const REDIS_HOST = process.env.REDIS_HOST ?? "redis"
export const REDIS_PORT = Number(process.env.REDIS_PORT ?? 6379)
export const MAIN_AGENT_MAX_ITERATIONS = 100
export const MAX_CONTEXT_WINDOW_LENGTH = 2_00_000
export const COMPACTION_PARAMETER = 10
export const COMPACT_THRESHOLD = 0.8*MAX_CONTEXT_WINDOW_LENGTH
export const CODER_MAX_ITERATIONS = 100
export const DEBUGGERR_MAX_ITERATIONS = 100
export const RESEARCHER_MAX_ITERATIONS = 100
export const TESTER_MAX_ITERATIONS = 50
export const UI_EXPERT_MAX_ITERATIONS = 50
export const TESTER_DEBUGGER_LOOP_MAX_ITERATIONS = 10
export const RECENT_TURNS_LIMIT = 20
export const RUN_COMMAND_TIMEOUT_MS = 300_000
export const SANDBOX_TIMEOUT_MS = 60 * 60 * 1000
export const SUBAGENT_LLM_RETRY_ATTEMPTS = 3
export const SUBAGENT_TOOL_RETRY_ATTEMPTS = 2
export const SUBAGENT_RETRY_BACKOFF_MS = 1000