/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { BamlRuntime, BamlCtxManager, Image, Audio, Pdf, Video, FunctionLog } from
"@boundaryml/baml"
import { toBamlError, HTTPRequest, ClientRegistry } from "@boundaryml/baml"
import type { Checked, Check } from "./types"
import type * as types from "./types"
import type {AgentResponse, ApifyRes, BraveRes, BraveResult, CoderContext, DebuggerResponse, DeleteFile, Done, Error, Errors, FetchDocs, FileEdit, FinalResponse, ItemRes, Message, Option, Question, ReadFile, Research, ResearcherResponse, Resume, RunCommand, Skill, SubAgent, Task, TaskComplexity, TesterResponse, Todo, WriteFile} from "./types"
import type TypeBuilder from "./type_builder"
import type * as events from "./events"

type TickReason = "Unknown";

type BamlCallOptions<EventsT = never> = {
tb?: TypeBuilder
clientRegistry?: ClientRegistry
client?: string
env?: Record<string, string | undefined>
  onTick?: (reason: TickReason, log: FunctionLog | null) => void
  events?: EventsT
  }

  export class AsyncHttpRequest {
  constructor(private runtime: BamlRuntime, private ctxManager: BamlCtxManager) {}

  
  async BugFinder(
  errors: string,systemPrompt: string,
  __baml_options__?: BamlCallOptions<never>
  ): Promise<HTTPRequest> {
    try {
    const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
    const __env__: Record<string, string> = Object.fromEntries(
      Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return await this.runtime.buildRequest(
      "BugFinder",
      {
      "errors": errors,"systemPrompt": systemPrompt
      },
      this.ctxManager.cloneContext(),
      __baml_options__?.tb?.__tb(),
      __clientRegistry__,
      false,
      __env__
      )
      } catch (error) {
      throw toBamlError(error);
      }
      }
      
  async CheckComplexityAndPlanTask(
  userPrompt: string,subAgents: types.SubAgent[],
  __baml_options__?: BamlCallOptions<never>
  ): Promise<HTTPRequest> {
    try {
    const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
    const __env__: Record<string, string> = Object.fromEntries(
      Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return await this.runtime.buildRequest(
      "CheckComplexityAndPlanTask",
      {
      "userPrompt": userPrompt,"subAgents": subAgents
      },
      this.ctxManager.cloneContext(),
      __baml_options__?.tb?.__tb(),
      __clientRegistry__,
      false,
      __env__
      )
      } catch (error) {
      throw toBamlError(error);
      }
      }
      
  async CoderAgent(
  prompt: string,systemPrompt: string,figmaBoilerPlate?: string | null,context: types.Message[],
  __baml_options__?: BamlCallOptions<never>
  ): Promise<HTTPRequest> {
    try {
    const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
    const __env__: Record<string, string> = Object.fromEntries(
      Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return await this.runtime.buildRequest(
      "CoderAgent",
      {
      "prompt": prompt,"systemPrompt": systemPrompt,"figmaBoilerPlate": figmaBoilerPlate?? null,"context": context
      },
      this.ctxManager.cloneContext(),
      __baml_options__?.tb?.__tb(),
      __clientRegistry__,
      false,
      __env__
      )
      } catch (error) {
      throw toBamlError(error);
      }
      }
      
  async DebuggerAgent(
  userPrompt: string,systemPrompt: string,errors: types.Error[],
  __baml_options__?: BamlCallOptions<never>
  ): Promise<HTTPRequest> {
    try {
    const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
    const __env__: Record<string, string> = Object.fromEntries(
      Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return await this.runtime.buildRequest(
      "DebuggerAgent",
      {
      "userPrompt": userPrompt,"systemPrompt": systemPrompt,"errors": errors
      },
      this.ctxManager.cloneContext(),
      __baml_options__?.tb?.__tb(),
      __clientRegistry__,
      false,
      __env__
      )
      } catch (error) {
      throw toBamlError(error);
      }
      }
      
  async ExtractErrors(
  query: string,systemPrompt: string,searchWay: string,
  __baml_options__?: BamlCallOptions<never>
  ): Promise<HTTPRequest> {
    try {
    const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
    const __env__: Record<string, string> = Object.fromEntries(
      Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return await this.runtime.buildRequest(
      "ExtractErrors",
      {
      "query": query,"systemPrompt": systemPrompt,"searchWay": searchWay
      },
      this.ctxManager.cloneContext(),
      __baml_options__?.tb?.__tb(),
      __clientRegistry__,
      false,
      __env__
      )
      } catch (error) {
      throw toBamlError(error);
      }
      }
      
  async ExtractResume(
  resume: string,
  __baml_options__?: BamlCallOptions<never>
  ): Promise<HTTPRequest> {
    try {
    const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
    const __env__: Record<string, string> = Object.fromEntries(
      Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return await this.runtime.buildRequest(
      "ExtractResume",
      {
      "resume": resume
      },
      this.ctxManager.cloneContext(),
      __baml_options__?.tb?.__tb(),
      __clientRegistry__,
      false,
      __env__
      )
      } catch (error) {
      throw toBamlError(error);
      }
      }
      
  async GenerateQuestion(
  prompt: string,questionPrompt: string,
  __baml_options__?: BamlCallOptions<never>
  ): Promise<HTTPRequest> {
    try {
    const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
    const __env__: Record<string, string> = Object.fromEntries(
      Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return await this.runtime.buildRequest(
      "GenerateQuestion",
      {
      "prompt": prompt,"questionPrompt": questionPrompt
      },
      this.ctxManager.cloneContext(),
      __baml_options__?.tb?.__tb(),
      __clientRegistry__,
      false,
      __env__
      )
      } catch (error) {
      throw toBamlError(error);
      }
      }
      
  async GetTodos(
  userPrompt: string,systemPrompt: string,
  __baml_options__?: BamlCallOptions<never>
  ): Promise<HTTPRequest> {
    try {
    const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
    const __env__: Record<string, string> = Object.fromEntries(
      Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return await this.runtime.buildRequest(
      "GetTodos",
      {
      "userPrompt": userPrompt,"systemPrompt": systemPrompt
      },
      this.ctxManager.cloneContext(),
      __baml_options__?.tb?.__tb(),
      __clientRegistry__,
      false,
      __env__
      )
      } catch (error) {
      throw toBamlError(error);
      }
      }
      
  async OrchestrateAgent(
  systemPrompt: string,
  __baml_options__?: BamlCallOptions<never>
  ): Promise<HTTPRequest> {
    try {
    const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
    const __env__: Record<string, string> = Object.fromEntries(
      Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return await this.runtime.buildRequest(
      "OrchestrateAgent",
      {
      "systemPrompt": systemPrompt
      },
      this.ctxManager.cloneContext(),
      __baml_options__?.tb?.__tb(),
      __clientRegistry__,
      false,
      __env__
      )
      } catch (error) {
      throw toBamlError(error);
      }
      }
      
  async ResearchAgent(
  query: string,systemPrompt: string,searchWay: string,
  __baml_options__?: BamlCallOptions<never>
  ): Promise<HTTPRequest> {
    try {
    const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
    const __env__: Record<string, string> = Object.fromEntries(
      Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return await this.runtime.buildRequest(
      "ResearchAgent",
      {
      "query": query,"systemPrompt": systemPrompt,"searchWay": searchWay
      },
      this.ctxManager.cloneContext(),
      __baml_options__?.tb?.__tb(),
      __clientRegistry__,
      false,
      __env__
      )
      } catch (error) {
      throw toBamlError(error);
      }
      }
      
  async StreamOneAgent(
  userPrompt: string,systemPrompt: string,
  __baml_options__?: BamlCallOptions<never>
  ): Promise<HTTPRequest> {
    try {
    const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
    const __env__: Record<string, string> = Object.fromEntries(
      Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return await this.runtime.buildRequest(
      "StreamOneAgent",
      {
      "userPrompt": userPrompt,"systemPrompt": systemPrompt
      },
      this.ctxManager.cloneContext(),
      __baml_options__?.tb?.__tb(),
      __clientRegistry__,
      false,
      __env__
      )
      } catch (error) {
      throw toBamlError(error);
      }
      }
      
  async TesterAgent(
  userPrompt: string,systemPrompt: string,
  __baml_options__?: BamlCallOptions<never>
  ): Promise<HTTPRequest> {
    try {
    const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
    const __env__: Record<string, string> = Object.fromEntries(
      Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return await this.runtime.buildRequest(
      "TesterAgent",
      {
      "userPrompt": userPrompt,"systemPrompt": systemPrompt
      },
      this.ctxManager.cloneContext(),
      __baml_options__?.tb?.__tb(),
      __clientRegistry__,
      false,
      __env__
      )
      } catch (error) {
      throw toBamlError(error);
      }
      }
      
      }

      export class AsyncHttpStreamRequest {
      constructor(private runtime: BamlRuntime, private ctxManager: BamlCtxManager) {}

      
      async BugFinder(
      errors: string,systemPrompt: string,
      __baml_options__?: BamlCallOptions<never>
      ): Promise<HTTPRequest> {
        try {
        const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
        const __env__: Record<string, string> = Object.fromEntries(
          Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
          );

          // Resolve client option to clientRegistry (client takes precedence)
          let __clientRegistry__ = __baml_options__?.clientRegistry;
          if (__baml_options__?.client) {
            __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
            __clientRegistry__.setPrimary(__baml_options__.client);
          }

          return await this.runtime.buildRequest(
          "BugFinder",
          {
          "errors": errors,"systemPrompt": systemPrompt
          },
          this.ctxManager.cloneContext(),
          __baml_options__?.tb?.__tb(),
          __clientRegistry__,
          true,
          __env__
          )
          } catch (error) {
          throw toBamlError(error);
          }
          }
          
      async CheckComplexityAndPlanTask(
      userPrompt: string,subAgents: types.SubAgent[],
      __baml_options__?: BamlCallOptions<never>
      ): Promise<HTTPRequest> {
        try {
        const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
        const __env__: Record<string, string> = Object.fromEntries(
          Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
          );

          // Resolve client option to clientRegistry (client takes precedence)
          let __clientRegistry__ = __baml_options__?.clientRegistry;
          if (__baml_options__?.client) {
            __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
            __clientRegistry__.setPrimary(__baml_options__.client);
          }

          return await this.runtime.buildRequest(
          "CheckComplexityAndPlanTask",
          {
          "userPrompt": userPrompt,"subAgents": subAgents
          },
          this.ctxManager.cloneContext(),
          __baml_options__?.tb?.__tb(),
          __clientRegistry__,
          true,
          __env__
          )
          } catch (error) {
          throw toBamlError(error);
          }
          }
          
      async CoderAgent(
      prompt: string,systemPrompt: string,figmaBoilerPlate?: string | null,context: types.Message[],
      __baml_options__?: BamlCallOptions<never>
      ): Promise<HTTPRequest> {
        try {
        const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
        const __env__: Record<string, string> = Object.fromEntries(
          Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
          );

          // Resolve client option to clientRegistry (client takes precedence)
          let __clientRegistry__ = __baml_options__?.clientRegistry;
          if (__baml_options__?.client) {
            __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
            __clientRegistry__.setPrimary(__baml_options__.client);
          }

          return await this.runtime.buildRequest(
          "CoderAgent",
          {
          "prompt": prompt,"systemPrompt": systemPrompt,"figmaBoilerPlate": figmaBoilerPlate?? null,"context": context
          },
          this.ctxManager.cloneContext(),
          __baml_options__?.tb?.__tb(),
          __clientRegistry__,
          true,
          __env__
          )
          } catch (error) {
          throw toBamlError(error);
          }
          }
          
      async DebuggerAgent(
      userPrompt: string,systemPrompt: string,errors: types.Error[],
      __baml_options__?: BamlCallOptions<never>
      ): Promise<HTTPRequest> {
        try {
        const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
        const __env__: Record<string, string> = Object.fromEntries(
          Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
          );

          // Resolve client option to clientRegistry (client takes precedence)
          let __clientRegistry__ = __baml_options__?.clientRegistry;
          if (__baml_options__?.client) {
            __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
            __clientRegistry__.setPrimary(__baml_options__.client);
          }

          return await this.runtime.buildRequest(
          "DebuggerAgent",
          {
          "userPrompt": userPrompt,"systemPrompt": systemPrompt,"errors": errors
          },
          this.ctxManager.cloneContext(),
          __baml_options__?.tb?.__tb(),
          __clientRegistry__,
          true,
          __env__
          )
          } catch (error) {
          throw toBamlError(error);
          }
          }
          
      async ExtractErrors(
      query: string,systemPrompt: string,searchWay: string,
      __baml_options__?: BamlCallOptions<never>
      ): Promise<HTTPRequest> {
        try {
        const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
        const __env__: Record<string, string> = Object.fromEntries(
          Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
          );

          // Resolve client option to clientRegistry (client takes precedence)
          let __clientRegistry__ = __baml_options__?.clientRegistry;
          if (__baml_options__?.client) {
            __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
            __clientRegistry__.setPrimary(__baml_options__.client);
          }

          return await this.runtime.buildRequest(
          "ExtractErrors",
          {
          "query": query,"systemPrompt": systemPrompt,"searchWay": searchWay
          },
          this.ctxManager.cloneContext(),
          __baml_options__?.tb?.__tb(),
          __clientRegistry__,
          true,
          __env__
          )
          } catch (error) {
          throw toBamlError(error);
          }
          }
          
      async ExtractResume(
      resume: string,
      __baml_options__?: BamlCallOptions<never>
      ): Promise<HTTPRequest> {
        try {
        const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
        const __env__: Record<string, string> = Object.fromEntries(
          Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
          );

          // Resolve client option to clientRegistry (client takes precedence)
          let __clientRegistry__ = __baml_options__?.clientRegistry;
          if (__baml_options__?.client) {
            __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
            __clientRegistry__.setPrimary(__baml_options__.client);
          }

          return await this.runtime.buildRequest(
          "ExtractResume",
          {
          "resume": resume
          },
          this.ctxManager.cloneContext(),
          __baml_options__?.tb?.__tb(),
          __clientRegistry__,
          true,
          __env__
          )
          } catch (error) {
          throw toBamlError(error);
          }
          }
          
      async GenerateQuestion(
      prompt: string,questionPrompt: string,
      __baml_options__?: BamlCallOptions<never>
      ): Promise<HTTPRequest> {
        try {
        const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
        const __env__: Record<string, string> = Object.fromEntries(
          Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
          );

          // Resolve client option to clientRegistry (client takes precedence)
          let __clientRegistry__ = __baml_options__?.clientRegistry;
          if (__baml_options__?.client) {
            __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
            __clientRegistry__.setPrimary(__baml_options__.client);
          }

          return await this.runtime.buildRequest(
          "GenerateQuestion",
          {
          "prompt": prompt,"questionPrompt": questionPrompt
          },
          this.ctxManager.cloneContext(),
          __baml_options__?.tb?.__tb(),
          __clientRegistry__,
          true,
          __env__
          )
          } catch (error) {
          throw toBamlError(error);
          }
          }
          
      async GetTodos(
      userPrompt: string,systemPrompt: string,
      __baml_options__?: BamlCallOptions<never>
      ): Promise<HTTPRequest> {
        try {
        const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
        const __env__: Record<string, string> = Object.fromEntries(
          Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
          );

          // Resolve client option to clientRegistry (client takes precedence)
          let __clientRegistry__ = __baml_options__?.clientRegistry;
          if (__baml_options__?.client) {
            __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
            __clientRegistry__.setPrimary(__baml_options__.client);
          }

          return await this.runtime.buildRequest(
          "GetTodos",
          {
          "userPrompt": userPrompt,"systemPrompt": systemPrompt
          },
          this.ctxManager.cloneContext(),
          __baml_options__?.tb?.__tb(),
          __clientRegistry__,
          true,
          __env__
          )
          } catch (error) {
          throw toBamlError(error);
          }
          }
          
      async OrchestrateAgent(
      systemPrompt: string,
      __baml_options__?: BamlCallOptions<never>
      ): Promise<HTTPRequest> {
        try {
        const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
        const __env__: Record<string, string> = Object.fromEntries(
          Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
          );

          // Resolve client option to clientRegistry (client takes precedence)
          let __clientRegistry__ = __baml_options__?.clientRegistry;
          if (__baml_options__?.client) {
            __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
            __clientRegistry__.setPrimary(__baml_options__.client);
          }

          return await this.runtime.buildRequest(
          "OrchestrateAgent",
          {
          "systemPrompt": systemPrompt
          },
          this.ctxManager.cloneContext(),
          __baml_options__?.tb?.__tb(),
          __clientRegistry__,
          true,
          __env__
          )
          } catch (error) {
          throw toBamlError(error);
          }
          }
          
      async ResearchAgent(
      query: string,systemPrompt: string,searchWay: string,
      __baml_options__?: BamlCallOptions<never>
      ): Promise<HTTPRequest> {
        try {
        const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
        const __env__: Record<string, string> = Object.fromEntries(
          Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
          );

          // Resolve client option to clientRegistry (client takes precedence)
          let __clientRegistry__ = __baml_options__?.clientRegistry;
          if (__baml_options__?.client) {
            __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
            __clientRegistry__.setPrimary(__baml_options__.client);
          }

          return await this.runtime.buildRequest(
          "ResearchAgent",
          {
          "query": query,"systemPrompt": systemPrompt,"searchWay": searchWay
          },
          this.ctxManager.cloneContext(),
          __baml_options__?.tb?.__tb(),
          __clientRegistry__,
          true,
          __env__
          )
          } catch (error) {
          throw toBamlError(error);
          }
          }
          
      async StreamOneAgent(
      userPrompt: string,systemPrompt: string,
      __baml_options__?: BamlCallOptions<never>
      ): Promise<HTTPRequest> {
        try {
        const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
        const __env__: Record<string, string> = Object.fromEntries(
          Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
          );

          // Resolve client option to clientRegistry (client takes precedence)
          let __clientRegistry__ = __baml_options__?.clientRegistry;
          if (__baml_options__?.client) {
            __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
            __clientRegistry__.setPrimary(__baml_options__.client);
          }

          return await this.runtime.buildRequest(
          "StreamOneAgent",
          {
          "userPrompt": userPrompt,"systemPrompt": systemPrompt
          },
          this.ctxManager.cloneContext(),
          __baml_options__?.tb?.__tb(),
          __clientRegistry__,
          true,
          __env__
          )
          } catch (error) {
          throw toBamlError(error);
          }
          }
          
      async TesterAgent(
      userPrompt: string,systemPrompt: string,
      __baml_options__?: BamlCallOptions<never>
      ): Promise<HTTPRequest> {
        try {
        const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
        const __env__: Record<string, string> = Object.fromEntries(
          Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
          );

          // Resolve client option to clientRegistry (client takes precedence)
          let __clientRegistry__ = __baml_options__?.clientRegistry;
          if (__baml_options__?.client) {
            __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
            __clientRegistry__.setPrimary(__baml_options__.client);
          }

          return await this.runtime.buildRequest(
          "TesterAgent",
          {
          "userPrompt": userPrompt,"systemPrompt": systemPrompt
          },
          this.ctxManager.cloneContext(),
          __baml_options__?.tb?.__tb(),
          __clientRegistry__,
          true,
          __env__
          )
          } catch (error) {
          throw toBamlError(error);
          }
          }
          
          }