/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
import type { Checked, Check } from "./types"
import type {  Agent,  AgentContext,  AgentResponse,  Apify,  ApifyRes,  BraveRes,  BraveResult,  CoderContext,  CoderSession,  ComplexComplexity,  Context7,  ContextType,  DebuggerContext,  DebuggerSession,  DebuggingDone,  Decision,  DeleteFile,  Design,  DesignVariants,  DocsSearch,  Done,  EditFile,  EpisodicMemory,  Error,  ErrorResponse,  FetchDocs,  FileEdit,  FinalResponse,  Fixes,  ItemRes,  LLMResponse,  Message,  PlannerTodo,  Question,  ReadFile,  Research,  ResearcherContext,  ResearcherResponse,  ResearcherSession,  RunCommand,  SessionMap,  SimpleComplexity,  StitchTool,  SubAgentsContexts,  TaskComplexity,  TaskSummary,  Tavily,  TesterContext,  TesterResponse,  TesterSession,  ToolCall,  ToolResult,  ToolType,  UIExpertContext,  UIExpertSession,  WebScrape,  WebSearch,  WriteFile } from "./types"
import type * as types from "./types"

/******************************************************************************
*
*  These types are used for streaming, for when an instance of a type
*  is still being built up and any of its fields is not yet fully available.
*
******************************************************************************/

export interface StreamState<T> {
  value: T
  state: "Pending" | "Incomplete" | "Complete"
}

export namespace partial_types {
    export interface AgentContext {
    }
    export interface AgentResponse {
    }
    export interface Apify {
      urls: string[]
      maxPages?: number | null
    }
    export interface ApifyRes {
      status?: string | null
      itemcount?: number | null
      scrapeRes: ItemRes[]
    }
    export interface BraveRes {
      type?: string | null
      result: BraveResult[]
    }
    export interface BraveResult {
      title?: string | null
      url?: string | null
      description?: string | null
      pageAge?: string | null
    }
    export interface CoderContext {
      task?: string | null
      dependentSummary: TaskSummary[]
      repoTree?: string | null
    }
    export interface CoderSession {
      taskId?: number | null
      role?: "user" | "assistant" | "tool" | null
      status?: "in_progress" | "halted" | "resolved" | "done" | null
      iterationCount?: number | null
      timestamp?: string | null
      content?: string | null
    }
    export interface ComplexComplexity {
      complex?: true | null
      questions: Question[]
    }
    export interface Context7 {
      library?: string | null
      query?: string | null
    }
    export interface DebuggerContext {
      repoTree?: string | null
      originalError?: string | null
      fixHistory: Fixes[]
    }
    export interface DebuggerSession {
      taskId?: number | null
      role?: "user" | "assistant" | "tool" | null
      status?: "in_progress" | "halted" | "resolved" | "done" | null
      iterationCount?: number | null
      timestamp?: string | null
      content?: string | null
      rawTranscript?: string | null
    }
    export interface DebuggingDone {
      action?: "done" | null
      editedFile: FileEdit[]
      errors: Record<string, string>
    }
    export interface Decision {
      actor?: string | null
      decision?: string | null
      accepted?: string | null
    }
    export interface DeleteFile {
      action?: "delete" | null
      path?: string | null
    }
    export interface Design {
      taskId?: number | null
      summary?: string | null
    }
    export interface DesignVariants {
      prompts: string[]
    }
    export interface DocsSearch {
      type?: "docsSearch" | null
      library?: string | null
      query?: string | null
    }
    export interface Done {
      action?: "done" | null
      filesEdited: FileEdit[]
    }
    export interface EditFile {
      action?: "editFile" | null
      path?: string | null
      content?: string | null
    }
    export interface EpisodicMemory {
      sessionGoal?: string | null
      userRequests: string[]
      impFacts: string[]
      decisions: string[]
      toolResults: string[]
      generatedArtifacts: string[]
      openTasks: string[]
      preferences: string[]
      entities: string[]
      summary?: string | null
    }
    export interface Error {
      fileName?: string | null
      error?: string | null
      source?: "tester" | "build" | "deploy" | null
    }
    export interface ErrorResponse {
      error?: string | null
      file?: string | null
      line?: number | null
    }
    export interface FetchDocs {
      action?: "fetchDocs" | null
      query?: string | null
      library?: string | null
    }
    export interface FileEdit {
      fileName?: string | null
      summary?: string | null
    }
    export interface FinalResponse {
      status?: "success" | "failed" | null
      previewUrl?: string | null
      deployUrl?: string | null
    }
    export interface Fixes {
      error?: string | null
      fixSummary?: string | null
    }
    export interface ItemRes {
      title?: string | null
      description?: string | null
      url?: string | null
    }
    export interface LLMResponse {
      stopReason?: "completed" | "aborted" | "toolCall" | null
      content?: string | null
      toolCall?: ToolCall | null
      questions?: Question[] | null
    }
    export interface Message {
      role?: "user" | "assistant" | "toolCall" | "system" | null
      content?: string | null
      timestamp?: string | null
    }
    export interface PlannerTodo {
      id?: number | null
      task?: string | null
      agent?: "coder" | "debuggerr" | "tester" | "researcher" | "uiExpert" | null
      status?: "pending" | "completed" | null
      dependency: number[]
      designNeeded?: boolean | null
    }
    export interface Question {
      question?: string | null
      option: string[]
    }
    export interface ReadFile {
      action?: "read" | null
      path?: string | null
    }
    export interface Research {
      action?: "research" | null
      searchType?: WebSearch | WebScrape | DocsSearch | null
    }
    export interface ResearcherContext {
      query?: string | null
    }
    export interface ResearcherResponse {
      query?: string | null
      result?: BraveRes | ApifyRes | null
    }
    export interface ResearcherSession {
      taskId?: number | null
      role?: "user" | "assistant" | "tool" | null
      status?: "in_progress" | "halted" | "resolved" | "done" | null
      iterationCount?: number | null
      timestamp?: string | null
      content?: string | null
    }
    export interface RunCommand {
      action?: "runCommand" | null
      command?: string | null
    }
    export interface SessionMap {
      coder?: CoderSession | null
      debuggerr?: DebuggerSession | null
      tester?: TesterSession | null
      researcher?: ResearcherSession | null
      uiExpert?: UIExpertSession | null
    }
    export interface SimpleComplexity {
      complex?: false | null
    }
    export interface StitchTool {
      prompt?: string | null
      userId?: string | null
    }
    export interface SubAgentsContexts {
      coder?: CoderContext | null
      debuggerr?: DebuggerContext | null
      tester?: TesterContext | null
      researcher?: ResearcherContext | null
      uiExpert?: UIExpertContext | null
    }
    export interface TaskComplexity {
      complexity?: boolean | null
      POA?: PlannerTodo[] | string | null
    }
    export interface TaskSummary {
      taskId?: string | null
      summary?: string | null
    }
    export interface Tavily {
      query?: string | null
      maxResults?: number | null
    }
    export interface TesterContext {
    }
    export interface TesterResponse {
    }
    export interface TesterSession {
      taskId?: number | null
      role?: "user" | "assistant" | "tool" | null
      status?: "in_progress" | "halted" | "resolved" | "done" | null
      iterationCount?: number | null
      timestamp?: string | null
      content?: string | null
    }
    export interface ToolCall {
      type?: types.ToolType | null
      apify?: Apify | null
      context7?: Context7 | null
      tavily?: Tavily | null
      stitch?: StitchTool | null
      readFile?: ReadFile | null
      writeFile?: WriteFile | null
      editFile?: EditFile | null
      runCommand?: RunCommand | null
      deleteFile?: DeleteFile | null
    }
    export interface ToolResult {
      success?: boolean | null
      content?: FileEdit[] | null
    }
    export interface UIExpertContext {
      userPrompt?: string | null
      priorDesigns: Design[]
    }
    export interface UIExpertSession {
      taskId?: number | null
      role?: "user" | "assistant" | "tool" | null
      status?: "in_progress" | "halted" | "resolved" | "done" | null
      iterationCount?: number | null
      timestamp?: string | null
      content?: string | null
    }
    export interface WebScrape {
      type?: "webScrape" | null
      urls: string[]
      maxPages?: number | null
    }
    export interface WebSearch {
      type?: "webSearch" | null
      query?: string | null
      maxResults?: number | null
    }
    export interface WriteFile {
      action?: "writeFile" | null
      path?: string | null
      content?: string | null
    }
export type ComplexityLevel = SimpleComplexity | ComplexComplexity | null

export type Role = "user" | "assistant" | "tool" | null

export type Status = "in_progress" | "halted" | "resolved" | "done" | null

export type SubAgentsContext = CoderContext | DebuggerContext | TesterContext | ResearcherContext | UIExpertContext | null

}