/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
import type { Checked, Check } from "./types"
import type {  Abort,  Agent,  AgentContext,  AgentResponse,  AgentSummary,  Apify,  ApifyRes,  BraveRes,  BraveResult,  CoderContext,  CoderSession,  ComplexityVerdict,  ConflictTaskInfo,  Context7,  ContextType,  ConversationalReply,  DebuggerContext,  DebuggerSession,  DebuggingDone,  Decision,  DeleteFile,  Design,  DesignVariants,  DevelopmentVerdict,  DocsSearch,  Done,  EditFile,  EpisodicMemory,  Error,  ErrorResponse,  FetchDocs,  FileEdit,  FileEditOp,  Fixes,  GetSkill,  ItemRes,  MergeConflictContext,  MergeConflictResolution,  Message,  PlanTasksOutput,  PlannedScreen,  PlannerTodo,  Question,  ReadFile,  Research,  ResearcherContext,  ResearcherResponse,  ResearcherSession,  RunCommand,  SessionMap,  Skill,  StitchTool,  SubAgentsContexts,  TaskComplexity,  TaskSummary,  Tavily,  TesterContext,  TesterResponse,  TesterSession,  ToolResult,  UIExpertContext,  UIExpertSession,  WebScrape,  WebSearch,  WriteFile } from "./types"
import type * as types from "./types"

/******************************************************************************
*
*  These types are used for streaming, for when an instance of a type
*  is still being built up and any of its fields is not yet fully available.
*
******************************************************************************/

export interface StreamState<T> {
  value: T
  state: "Pending" | "Incomplete" | "Complete"
}

export namespace partial_types {
    export interface Abort {
      action?: "abort" | null
      reason?: string | null
    }
    export interface AgentContext {
    }
    export interface AgentResponse {
    }
    export interface AgentSummary {
      title?: string | null
      summary?: string | null
    }
    export interface Apify {
      action?: "apify" | null
      urls: string[]
      maxPages?: number | null
    }
    export interface ApifyRes {
      status?: string | null
      itemcount?: number | null
      scrapeRes: ItemRes[]
    }
    export interface BraveRes {
      type?: string | null
      result: BraveResult[]
    }
    export interface BraveResult {
      title?: string | null
      url?: string | null
      description?: string | null
      pageAge?: string | null
    }
    export interface CoderContext {
      task?: string | null
      description?: string | null
      expectedToolCalls?: number | null
      dependentSummary: TaskSummary[]
      repoTree?: string | null
      skills: Skill[]
      recentTurns: Message[]
    }
    export interface CoderSession {
      taskId?: number | null
      role?: "user" | "assistant" | "tool" | null
      status?: "in_progress" | "halted" | "resolved" | "done" | null
      iterationCount?: number | null
      timestamp?: string | null
      content?: string | null
    }
    export interface ComplexityVerdict {
      reasoning?: string | null
      complex?: boolean | null
    }
    export interface ConflictTaskInfo {
      task?: string | null
      summary?: string | null
    }
    export interface Context7 {
      action?: "context7" | null
      library?: string | null
      query?: string | null
    }
    export interface ConversationalReply {
      reply?: string | null
    }
    export interface DebuggerContext {
      repoTree?: string | null
      originalError?: string | null
      fixHistory: Fixes[]
      skills: Skill[]
      recentTurns: Message[]
    }
    export interface DebuggerSession {
      taskId?: number | null
      role?: "user" | "assistant" | "tool" | null
      status?: "in_progress" | "halted" | "resolved" | "done" | null
      iterationCount?: number | null
      timestamp?: string | null
      content?: string | null
      rawTranscript?: string | null
    }
    export interface DebuggingDone {
      action?: "done" | null
      editedFile: FileEdit[]
      errors: Record<string, string>
    }
    export interface Decision {
      actor?: string | null
      decision?: string | null
      accepted?: string | null
    }
    export interface DeleteFile {
      action?: "delete" | null
      path?: string | null
    }
    export interface Design {
      taskId?: number | null
      summary?: string | null
    }
    export interface DesignVariants {
      prompts: string[]
    }
    export interface DevelopmentVerdict {
      isDevelopment?: boolean | null
    }
    export interface DocsSearch {
      type?: "docsSearch" | null
      library?: string | null
      query?: string | null
    }
    export interface Done {
      action?: "done" | null
      filesEdited: FileEdit[]
    }
    export interface EditFile {
      action?: "editFile" | null
      path?: string | null
      edits: FileEditOp[]
    }
    export interface EpisodicMemory {
      sessionGoal?: string | null
      userRequests: string[]
      impFacts: string[]
      decisions: string[]
      toolResults: string[]
      generatedArtifacts: string[]
      openTasks: string[]
      preferences: string[]
      entities: string[]
      summary?: string | null
    }
    export interface Error {
      fileName?: string | null
      error?: string | null
      source?: "tester" | "build" | "deploy" | null
      taskId?: number | null
    }
    export interface ErrorResponse {
      error?: string | null
      file?: string | null
      line?: number | null
    }
    export interface FetchDocs {
      action?: "fetchDocs" | null
      query?: string | null
      library?: string | null
    }
    export interface FileEdit {
      fileName?: string | null
      summary?: string | null
    }
    export interface FileEditOp {
      oldString?: string | null
      newString?: string | null
    }
    export interface Fixes {
      error?: string | null
      fixSummary?: string | null
    }
    export interface GetSkill {
      action?: "getSkill" | null
      skillName?: string | null
    }
    export interface ItemRes {
      title?: string | null
      description?: string | null
      url?: string | null
    }
    export interface MergeConflictContext {
      filePath?: string | null
      conflictKind?: "content" | "deletedByTrunk" | "deletedByTask" | null
      conflictText?: string | null
      currentTask?: ConflictTaskInfo | null
      trunkTask?: ConflictTaskInfo | null
    }
    export interface MergeConflictResolution {
      reasoning?: string | null
      resolved?: boolean | null
      content?: string | null
    }
    export interface Message {
      role?: "user" | "assistant" | "toolCall" | "system" | null
      content?: string | null
      timestamp?: string | null
    }
    export interface PlanTasksOutput {
      reasoning?: string | null
      todos: PlannerTodo[]
    }
    export interface PlannedScreen {
      id?: string | null
      name?: string | null
      designBrief?: string | null
    }
    export interface PlannerTodo {
      id?: number | null
      task?: string | null
      description?: string | null
      agent?: "coder" | "uiExpert" | null
      designRef?: string | null
      status?: "pending" | "completed" | null
      dependency: number[]
      expectedToolCalls?: number | null
    }
    export interface Question {
      question?: string | null
      option: string[]
    }
    export interface ReadFile {
      action?: "read" | null
      path?: string | null
    }
    export interface Research {
      action?: "research" | null
      searchType?: WebSearch | WebScrape | DocsSearch | null
    }
    export interface ResearcherContext {
      query?: string | null
      skills: Skill[]
    }
    export interface ResearcherResponse {
      query?: string | null
      result?: BraveRes | ApifyRes | null
    }
    export interface ResearcherSession {
      taskId?: number | null
      role?: "user" | "assistant" | "tool" | null
      status?: "in_progress" | "halted" | "resolved" | "done" | null
      iterationCount?: number | null
      timestamp?: string | null
      content?: string | null
    }
    export interface RunCommand {
      action?: "runCommand" | null
      command?: string | null
      cwd?: string | null
    }
    export interface SessionMap {
      coder?: CoderSession | null
      debuggerr?: DebuggerSession | null
      tester?: TesterSession | null
      researcher?: ResearcherSession | null
      uiExpert?: UIExpertSession | null
    }
    export interface Skill {
      name?: string | null
      description?: string | null
      content?: string | null
    }
    export interface StitchTool {
      action?: "stitch" | null
      prompt?: string | null
      userId?: string | null
    }
    export interface SubAgentsContexts {
      coder?: CoderContext | null
      debuggerr?: DebuggerContext | null
      tester?: TesterContext | null
      researcher?: ResearcherContext | null
      uiExpert?: UIExpertContext | null
    }
    export interface TaskComplexity {
      complexity?: boolean | null
      POA?: PlannerTodo[] | string | null
    }
    export interface TaskSummary {
      taskId?: string | null
      summary?: string | null
    }
    export interface Tavily {
      action?: "tavily" | null
      query?: string | null
      maxResults?: number | null
    }
    export interface TesterContext {
      skills: Skill[]
    }
    export interface TesterResponse {
    }
    export interface TesterSession {
      taskId?: number | null
      role?: "user" | "assistant" | "tool" | null
      status?: "in_progress" | "halted" | "resolved" | "done" | null
      iterationCount?: number | null
      timestamp?: string | null
      content?: string | null
    }
    export interface ToolResult {
      success?: boolean | null
      content?: FileEdit[] | null
    }
    export interface UIExpertContext {
      userPrompt?: string | null
      priorDesigns: Design[]
      skills: Skill[]
    }
    export interface UIExpertSession {
      taskId?: number | null
      role?: "user" | "assistant" | "tool" | null
      status?: "in_progress" | "halted" | "resolved" | "done" | null
      iterationCount?: number | null
      timestamp?: string | null
      content?: string | null
    }
    export interface WebScrape {
      type?: "webScrape" | null
      urls: string[]
      maxPages?: number | null
    }
    export interface WebSearch {
      type?: "webSearch" | null
      query?: string | null
      maxResults?: number | null
    }
    export interface WriteFile {
      action?: "writeFile" | null
      path?: string | null
      content?: string | null
    }
export type Role = "user" | "assistant" | "tool" | null

export type Status = "in_progress" | "halted" | "resolved" | "done" | null

export type SubAgentsContext = CoderContext | DebuggerContext | TesterContext | ResearcherContext | UIExpertContext | null

}