/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { BamlRuntime, FunctionResult, BamlCtxManager, Image, Audio, Pdf, Video, Collector, FunctionLog } from "@boundaryml/baml"
import { toBamlError, BamlAbortError, ClientRegistry, type HTTPRequest } from "@boundaryml/baml"
import type { Checked, Check, RecursivePartialNull as MovedRecursivePartialNull } from "./types"
import type * as types from "./types"
import type {Agent, AgentContext, AgentResponse, Apify, ApifyRes, BraveRes, BraveResult, CoderContext, ComplexComplexity, Context7, ContextType, DebuggerContext, DebuggingDone, Decision, DeleteFile, Design, DocsSearch, Done, EditFile, EpisodicMemory, Error, ErrorResponse, FetchDocs, FileEdit, FinalResponse, Fixes, ItemRes, LLMResponse, Message, PlannerTodo, Question, ReadFile, Research, ResearcherContext, ResearcherResponse, RunCommand, SimpleComplexity, StitchTool, SubAgentsContexts, TaskComplexity, TaskSummary, Tavily, TesterContext, TesterResponse, ToolCall, ToolResult, ToolType, UIExpertContext, WebScrape, WebSearch, WriteFile} from "./types"
import type TypeBuilder from "./type_builder"
import { HttpRequest, HttpStreamRequest } from "./sync_request"
import { LlmResponseParser, LlmStreamParser } from "./parser"
import { DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_CTX, DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME } from "./globals"
import type * as events from "./events"

/**
 * @deprecated Use RecursivePartialNull from 'baml_client/types' instead.
 * Example:
 * ```ts
 * import { RecursivePartialNull } from './baml_client/types'
 * ```
 */
export type RecursivePartialNull<T> = MovedRecursivePartialNull<T>;

type TickReason = "Unknown";

type BamlCallOptions<WatchersT = never> = {
  tb?: TypeBuilder
  clientRegistry?: ClientRegistry
  client?: string
  collector?: Collector | Collector[]
  env?: Record<string, string | undefined>
  tags?: Record<string, string>
  signal?: AbortSignal
  onTick?: (reason: TickReason, log: FunctionLog | null) => void
  watchers?: WatchersT
}

export class BamlSyncClient {
  private httpRequest: HttpRequest
  private httpStreamRequest: HttpStreamRequest
  private llmResponseParser: LlmResponseParser
  private llmStreamParser: LlmStreamParser
  private bamlOptions: BamlCallOptions

  constructor(private runtime: BamlRuntime, private ctxManager: BamlCtxManager, bamlOptions?: BamlCallOptions) {
    this.httpRequest = new HttpRequest(runtime, ctxManager)
    this.httpStreamRequest = new HttpStreamRequest(runtime, ctxManager)
    this.llmResponseParser = new LlmResponseParser(runtime, ctxManager)
    this.llmStreamParser = new LlmStreamParser(runtime, ctxManager)
    this.bamlOptions = bamlOptions || {}
  }

  withOptions(bamlOptions: BamlCallOptions) {
    return new BamlSyncClient(this.runtime, this.ctxManager, bamlOptions)
  }

  /*
  * @deprecated NOT IMPLEMENTED as streaming must by async. We
  * are not providing an async version as we want to reserve the
  * right to provide a sync version in the future.
  */
  get stream() {
    throw new Error("stream is not available in BamlSyncClient. Use `import { b } from 'baml_client/async_client")
  }

  get request() {
    return this.httpRequest
  }

  get streamRequest() {
    return this.httpStreamRequest
  }

  get parse() {
    return this.llmResponseParser
  }

  get parseStream() {
    return this.llmStreamParser
  }

  
  BugFinder(
      errors: string,systemPrompt: string,
      __baml_options__?: BamlCallOptions<never>
  ): types.Error[] {
    try {
      const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
      const __signal__ = __options__.signal;

      if (__signal__?.aborted) {
        throw new BamlAbortError('Operation was aborted', __signal__.reason);
      }

      // Check if onTick is provided and reject for sync operations
      if (__options__.onTick) {
        throw new Error("onTick is not supported for synchronous functions. Please use the async client instead.");
      }

      const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector : [__options__.collector]) : [];
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __options__.clientRegistry;
      if (__options__.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__options__.client);
      }

      const __raw__ = this.runtime.callFunctionSync(
        "BugFinder",
        {
          "errors": errors,"systemPrompt": systemPrompt
        },
        this.ctxManager.cloneContext(),
        __options__.tb?.__tb(),
        __clientRegistry__,
        __collector__,
        __options__.tags || {},
        __env__,
        __signal__,
        __options__.watchers,
      )
      return __raw__.parsed(false) as types.Error[]
    } catch (error: any) {
      throw toBamlError(error);
    }
  }
  
  CheckComplexityAndGenerateQuestions(
      systemPrompt: string,userPrompt: string,
      __baml_options__?: BamlCallOptions<never>
  ): types.SimpleComplexity | types.ComplexComplexity {
    try {
      const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
      const __signal__ = __options__.signal;

      if (__signal__?.aborted) {
        throw new BamlAbortError('Operation was aborted', __signal__.reason);
      }

      // Check if onTick is provided and reject for sync operations
      if (__options__.onTick) {
        throw new Error("onTick is not supported for synchronous functions. Please use the async client instead.");
      }

      const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector : [__options__.collector]) : [];
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __options__.clientRegistry;
      if (__options__.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__options__.client);
      }

      const __raw__ = this.runtime.callFunctionSync(
        "CheckComplexityAndGenerateQuestions",
        {
          "systemPrompt": systemPrompt,"userPrompt": userPrompt
        },
        this.ctxManager.cloneContext(),
        __options__.tb?.__tb(),
        __clientRegistry__,
        __collector__,
        __options__.tags || {},
        __env__,
        __signal__,
        __options__.watchers,
      )
      return __raw__.parsed(false) as types.SimpleComplexity | types.ComplexComplexity
    } catch (error: any) {
      throw toBamlError(error);
    }
  }
  
  CoderAgent(
      systemPrompt: string,figmaBoilerPlate?: string | null,context: types.CoderContext,
      __baml_options__?: BamlCallOptions<never>
  ): types.WriteFile | types.ReadFile | types.EditFile | types.RunCommand | types.DeleteFile | types.Research | types.Done {
    try {
      const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
      const __signal__ = __options__.signal;

      if (__signal__?.aborted) {
        throw new BamlAbortError('Operation was aborted', __signal__.reason);
      }

      // Check if onTick is provided and reject for sync operations
      if (__options__.onTick) {
        throw new Error("onTick is not supported for synchronous functions. Please use the async client instead.");
      }

      const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector : [__options__.collector]) : [];
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __options__.clientRegistry;
      if (__options__.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__options__.client);
      }

      const __raw__ = this.runtime.callFunctionSync(
        "CoderAgent",
        {
          "systemPrompt": systemPrompt,"figmaBoilerPlate": figmaBoilerPlate?? null,"context": context
        },
        this.ctxManager.cloneContext(),
        __options__.tb?.__tb(),
        __clientRegistry__,
        __collector__,
        __options__.tags || {},
        __env__,
        __signal__,
        __options__.watchers,
      )
      return __raw__.parsed(false) as types.WriteFile | types.ReadFile | types.EditFile | types.RunCommand | types.DeleteFile | types.Research | types.Done
    } catch (error: any) {
      throw toBamlError(error);
    }
  }
  
  CompactCoderContext(
      systemPrompt: string,context: types.CoderContext,
      __baml_options__?: BamlCallOptions<never>
  ): types.CoderContext {
    try {
      const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
      const __signal__ = __options__.signal;

      if (__signal__?.aborted) {
        throw new BamlAbortError('Operation was aborted', __signal__.reason);
      }

      // Check if onTick is provided and reject for sync operations
      if (__options__.onTick) {
        throw new Error("onTick is not supported for synchronous functions. Please use the async client instead.");
      }

      const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector : [__options__.collector]) : [];
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __options__.clientRegistry;
      if (__options__.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__options__.client);
      }

      const __raw__ = this.runtime.callFunctionSync(
        "CompactCoderContext",
        {
          "systemPrompt": systemPrompt,"context": context
        },
        this.ctxManager.cloneContext(),
        __options__.tb?.__tb(),
        __clientRegistry__,
        __collector__,
        __options__.tags || {},
        __env__,
        __signal__,
        __options__.watchers,
      )
      return __raw__.parsed(false) as types.CoderContext
    } catch (error: any) {
      throw toBamlError(error);
    }
  }
  
  CompactContext(
      systemPrompt: string,context: types.Message[],
      __baml_options__?: BamlCallOptions<never>
  ): types.Message[] {
    try {
      const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
      const __signal__ = __options__.signal;

      if (__signal__?.aborted) {
        throw new BamlAbortError('Operation was aborted', __signal__.reason);
      }

      // Check if onTick is provided and reject for sync operations
      if (__options__.onTick) {
        throw new Error("onTick is not supported for synchronous functions. Please use the async client instead.");
      }

      const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector : [__options__.collector]) : [];
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __options__.clientRegistry;
      if (__options__.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__options__.client);
      }

      const __raw__ = this.runtime.callFunctionSync(
        "CompactContext",
        {
          "systemPrompt": systemPrompt,"context": context
        },
        this.ctxManager.cloneContext(),
        __options__.tb?.__tb(),
        __clientRegistry__,
        __collector__,
        __options__.tags || {},
        __env__,
        __signal__,
        __options__.watchers,
      )
      return __raw__.parsed(false) as types.Message[]
    } catch (error: any) {
      throw toBamlError(error);
    }
  }
  
  CompactDebuggerContext(
      systemPrompt: string,context: types.DebuggerContext,
      __baml_options__?: BamlCallOptions<never>
  ): types.DebuggerContext {
    try {
      const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
      const __signal__ = __options__.signal;

      if (__signal__?.aborted) {
        throw new BamlAbortError('Operation was aborted', __signal__.reason);
      }

      // Check if onTick is provided and reject for sync operations
      if (__options__.onTick) {
        throw new Error("onTick is not supported for synchronous functions. Please use the async client instead.");
      }

      const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector : [__options__.collector]) : [];
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __options__.clientRegistry;
      if (__options__.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__options__.client);
      }

      const __raw__ = this.runtime.callFunctionSync(
        "CompactDebuggerContext",
        {
          "systemPrompt": systemPrompt,"context": context
        },
        this.ctxManager.cloneContext(),
        __options__.tb?.__tb(),
        __clientRegistry__,
        __collector__,
        __options__.tags || {},
        __env__,
        __signal__,
        __options__.watchers,
      )
      return __raw__.parsed(false) as types.DebuggerContext
    } catch (error: any) {
      throw toBamlError(error);
    }
  }
  
  CompressContext(
      systemPrompt: string,session: string[],
      __baml_options__?: BamlCallOptions<never>
  ): types.EpisodicMemory {
    try {
      const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
      const __signal__ = __options__.signal;

      if (__signal__?.aborted) {
        throw new BamlAbortError('Operation was aborted', __signal__.reason);
      }

      // Check if onTick is provided and reject for sync operations
      if (__options__.onTick) {
        throw new Error("onTick is not supported for synchronous functions. Please use the async client instead.");
      }

      const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector : [__options__.collector]) : [];
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __options__.clientRegistry;
      if (__options__.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__options__.client);
      }

      const __raw__ = this.runtime.callFunctionSync(
        "CompressContext",
        {
          "systemPrompt": systemPrompt,"session": session
        },
        this.ctxManager.cloneContext(),
        __options__.tb?.__tb(),
        __clientRegistry__,
        __collector__,
        __options__.tags || {},
        __env__,
        __signal__,
        __options__.watchers,
      )
      return __raw__.parsed(false) as types.EpisodicMemory
    } catch (error: any) {
      throw toBamlError(error);
    }
  }
  
  DebuggerAgent(
      systemPrompt: string,errors: types.Error[],context: types.DebuggerContext,toolResult?: types.ToolResult | null,
      __baml_options__?: BamlCallOptions<never>
  ): types.ReadFile | types.RunCommand | types.WriteFile | types.EditFile | types.Research | types.DebuggingDone {
    try {
      const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
      const __signal__ = __options__.signal;

      if (__signal__?.aborted) {
        throw new BamlAbortError('Operation was aborted', __signal__.reason);
      }

      // Check if onTick is provided and reject for sync operations
      if (__options__.onTick) {
        throw new Error("onTick is not supported for synchronous functions. Please use the async client instead.");
      }

      const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector : [__options__.collector]) : [];
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __options__.clientRegistry;
      if (__options__.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__options__.client);
      }

      const __raw__ = this.runtime.callFunctionSync(
        "DebuggerAgent",
        {
          "systemPrompt": systemPrompt,"errors": errors,"context": context,"toolResult": toolResult?? null
        },
        this.ctxManager.cloneContext(),
        __options__.tb?.__tb(),
        __clientRegistry__,
        __collector__,
        __options__.tags || {},
        __env__,
        __signal__,
        __options__.watchers,
      )
      return __raw__.parsed(false) as types.ReadFile | types.RunCommand | types.WriteFile | types.EditFile | types.Research | types.DebuggingDone
    } catch (error: any) {
      throw toBamlError(error);
    }
  }
  
  FramePrompts(
      systemPrompt: string,userPrompt: string,semanticMem: string,
      __baml_options__?: BamlCallOptions<never>
  ): string {
    try {
      const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
      const __signal__ = __options__.signal;

      if (__signal__?.aborted) {
        throw new BamlAbortError('Operation was aborted', __signal__.reason);
      }

      // Check if onTick is provided and reject for sync operations
      if (__options__.onTick) {
        throw new Error("onTick is not supported for synchronous functions. Please use the async client instead.");
      }

      const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector : [__options__.collector]) : [];
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __options__.clientRegistry;
      if (__options__.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__options__.client);
      }

      const __raw__ = this.runtime.callFunctionSync(
        "FramePrompts",
        {
          "systemPrompt": systemPrompt,"userPrompt": userPrompt,"semanticMem": semanticMem
        },
        this.ctxManager.cloneContext(),
        __options__.tb?.__tb(),
        __clientRegistry__,
        __collector__,
        __options__.tags || {},
        __env__,
        __signal__,
        __options__.watchers,
      )
      return __raw__.parsed(false) as string
    } catch (error: any) {
      throw toBamlError(error);
    }
  }
  
  GenerateMainAgentSummary(
      systemPrompt: string,context: types.Message[],
      __baml_options__?: BamlCallOptions<never>
  ): string {
    try {
      const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
      const __signal__ = __options__.signal;

      if (__signal__?.aborted) {
        throw new BamlAbortError('Operation was aborted', __signal__.reason);
      }

      // Check if onTick is provided and reject for sync operations
      if (__options__.onTick) {
        throw new Error("onTick is not supported for synchronous functions. Please use the async client instead.");
      }

      const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector : [__options__.collector]) : [];
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __options__.clientRegistry;
      if (__options__.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__options__.client);
      }

      const __raw__ = this.runtime.callFunctionSync(
        "GenerateMainAgentSummary",
        {
          "systemPrompt": systemPrompt,"context": context
        },
        this.ctxManager.cloneContext(),
        __options__.tb?.__tb(),
        __clientRegistry__,
        __collector__,
        __options__.tags || {},
        __env__,
        __signal__,
        __options__.watchers,
      )
      return __raw__.parsed(false) as string
    } catch (error: any) {
      throw toBamlError(error);
    }
  }
  
  GenerateSubagentSummary(
      systemPrompt: string,subagentType: string,context: types.CoderContext | types.DebuggerContext | types.TesterContext | types.ResearcherContext | types.UIExpertContext,
      __baml_options__?: BamlCallOptions<never>
  ): string {
    try {
      const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
      const __signal__ = __options__.signal;

      if (__signal__?.aborted) {
        throw new BamlAbortError('Operation was aborted', __signal__.reason);
      }

      // Check if onTick is provided and reject for sync operations
      if (__options__.onTick) {
        throw new Error("onTick is not supported for synchronous functions. Please use the async client instead.");
      }

      const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector : [__options__.collector]) : [];
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __options__.clientRegistry;
      if (__options__.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__options__.client);
      }

      const __raw__ = this.runtime.callFunctionSync(
        "GenerateSubagentSummary",
        {
          "systemPrompt": systemPrompt,"subagentType": subagentType,"context": context
        },
        this.ctxManager.cloneContext(),
        __options__.tb?.__tb(),
        __clientRegistry__,
        __collector__,
        __options__.tags || {},
        __env__,
        __signal__,
        __options__.watchers,
      )
      return __raw__.parsed(false) as string
    } catch (error: any) {
      throw toBamlError(error);
    }
  }
  
  MainLLMCall(
      systemPrompt: string,design?: string | null,userPrompt: string,context: types.Message[],semanticMem: string,
      __baml_options__?: BamlCallOptions<never>
  ): types.LLMResponse {
    try {
      const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
      const __signal__ = __options__.signal;

      if (__signal__?.aborted) {
        throw new BamlAbortError('Operation was aborted', __signal__.reason);
      }

      // Check if onTick is provided and reject for sync operations
      if (__options__.onTick) {
        throw new Error("onTick is not supported for synchronous functions. Please use the async client instead.");
      }

      const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector : [__options__.collector]) : [];
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __options__.clientRegistry;
      if (__options__.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__options__.client);
      }

      const __raw__ = this.runtime.callFunctionSync(
        "MainLLMCall",
        {
          "systemPrompt": systemPrompt,"design": design?? null,"userPrompt": userPrompt,"context": context,"semanticMem": semanticMem
        },
        this.ctxManager.cloneContext(),
        __options__.tb?.__tb(),
        __clientRegistry__,
        __collector__,
        __options__.tags || {},
        __env__,
        __signal__,
        __options__.watchers,
      )
      return __raw__.parsed(false) as types.LLMResponse
    } catch (error: any) {
      throw toBamlError(error);
    }
  }
  
  OrchestrateAgent(
      systemPrompt: string,
      __baml_options__?: BamlCallOptions<never>
  ): types.FinalResponse {
    try {
      const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
      const __signal__ = __options__.signal;

      if (__signal__?.aborted) {
        throw new BamlAbortError('Operation was aborted', __signal__.reason);
      }

      // Check if onTick is provided and reject for sync operations
      if (__options__.onTick) {
        throw new Error("onTick is not supported for synchronous functions. Please use the async client instead.");
      }

      const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector : [__options__.collector]) : [];
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __options__.clientRegistry;
      if (__options__.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__options__.client);
      }

      const __raw__ = this.runtime.callFunctionSync(
        "OrchestrateAgent",
        {
          "systemPrompt": systemPrompt
        },
        this.ctxManager.cloneContext(),
        __options__.tb?.__tb(),
        __clientRegistry__,
        __collector__,
        __options__.tags || {},
        __env__,
        __signal__,
        __options__.watchers,
      )
      return __raw__.parsed(false) as types.FinalResponse
    } catch (error: any) {
      throw toBamlError(error);
    }
  }
  
  OrchestratorSummary(
      systemPrompt: string,summaries: string[],
      __baml_options__?: BamlCallOptions<never>
  ): string {
    try {
      const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
      const __signal__ = __options__.signal;

      if (__signal__?.aborted) {
        throw new BamlAbortError('Operation was aborted', __signal__.reason);
      }

      // Check if onTick is provided and reject for sync operations
      if (__options__.onTick) {
        throw new Error("onTick is not supported for synchronous functions. Please use the async client instead.");
      }

      const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector : [__options__.collector]) : [];
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __options__.clientRegistry;
      if (__options__.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__options__.client);
      }

      const __raw__ = this.runtime.callFunctionSync(
        "OrchestratorSummary",
        {
          "systemPrompt": systemPrompt,"summaries": summaries
        },
        this.ctxManager.cloneContext(),
        __options__.tb?.__tb(),
        __clientRegistry__,
        __collector__,
        __options__.tags || {},
        __env__,
        __signal__,
        __options__.watchers,
      )
      return __raw__.parsed(false) as string
    } catch (error: any) {
      throw toBamlError(error);
    }
  }
  
  PlanComplexTask(
      systemPrompt: string,userPrompt: string,design: string,context: string,
      __baml_options__?: BamlCallOptions<never>
  ): types.PlannerTodo[] {
    try {
      const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
      const __signal__ = __options__.signal;

      if (__signal__?.aborted) {
        throw new BamlAbortError('Operation was aborted', __signal__.reason);
      }

      // Check if onTick is provided and reject for sync operations
      if (__options__.onTick) {
        throw new Error("onTick is not supported for synchronous functions. Please use the async client instead.");
      }

      const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector : [__options__.collector]) : [];
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __options__.clientRegistry;
      if (__options__.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__options__.client);
      }

      const __raw__ = this.runtime.callFunctionSync(
        "PlanComplexTask",
        {
          "systemPrompt": systemPrompt,"userPrompt": userPrompt,"design": design,"context": context
        },
        this.ctxManager.cloneContext(),
        __options__.tb?.__tb(),
        __clientRegistry__,
        __collector__,
        __options__.tags || {},
        __env__,
        __signal__,
        __options__.watchers,
      )
      return __raw__.parsed(false) as types.PlannerTodo[]
    } catch (error: any) {
      throw toBamlError(error);
    }
  }
  
  ReframeError(
      systemPrompt: string,error: string,
      __baml_options__?: BamlCallOptions<never>
  ): types.ErrorResponse {
    try {
      const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
      const __signal__ = __options__.signal;

      if (__signal__?.aborted) {
        throw new BamlAbortError('Operation was aborted', __signal__.reason);
      }

      // Check if onTick is provided and reject for sync operations
      if (__options__.onTick) {
        throw new Error("onTick is not supported for synchronous functions. Please use the async client instead.");
      }

      const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector : [__options__.collector]) : [];
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __options__.clientRegistry;
      if (__options__.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__options__.client);
      }

      const __raw__ = this.runtime.callFunctionSync(
        "ReframeError",
        {
          "systemPrompt": systemPrompt,"error": error
        },
        this.ctxManager.cloneContext(),
        __options__.tb?.__tb(),
        __clientRegistry__,
        __collector__,
        __options__.tags || {},
        __env__,
        __signal__,
        __options__.watchers,
      )
      return __raw__.parsed(false) as types.ErrorResponse
    } catch (error: any) {
      throw toBamlError(error);
    }
  }
  
  ResearchAgent(
      query: string,systemPrompt: string,searchWay: string,
      __baml_options__?: BamlCallOptions<never>
  ): types.ResearcherResponse {
    try {
      const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
      const __signal__ = __options__.signal;

      if (__signal__?.aborted) {
        throw new BamlAbortError('Operation was aborted', __signal__.reason);
      }

      // Check if onTick is provided and reject for sync operations
      if (__options__.onTick) {
        throw new Error("onTick is not supported for synchronous functions. Please use the async client instead.");
      }

      const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector : [__options__.collector]) : [];
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __options__.clientRegistry;
      if (__options__.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__options__.client);
      }

      const __raw__ = this.runtime.callFunctionSync(
        "ResearchAgent",
        {
          "query": query,"systemPrompt": systemPrompt,"searchWay": searchWay
        },
        this.ctxManager.cloneContext(),
        __options__.tb?.__tb(),
        __clientRegistry__,
        __collector__,
        __options__.tags || {},
        __env__,
        __signal__,
        __options__.watchers,
      )
      return __raw__.parsed(false) as types.ResearcherResponse
    } catch (error: any) {
      throw toBamlError(error);
    }
  }
  
  StreamOneAgent(
      userPrompt: string,systemPrompt: string,
      __baml_options__?: BamlCallOptions<never>
  ): types.AgentResponse {
    try {
      const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
      const __signal__ = __options__.signal;

      if (__signal__?.aborted) {
        throw new BamlAbortError('Operation was aborted', __signal__.reason);
      }

      // Check if onTick is provided and reject for sync operations
      if (__options__.onTick) {
        throw new Error("onTick is not supported for synchronous functions. Please use the async client instead.");
      }

      const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector : [__options__.collector]) : [];
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __options__.clientRegistry;
      if (__options__.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__options__.client);
      }

      const __raw__ = this.runtime.callFunctionSync(
        "StreamOneAgent",
        {
          "userPrompt": userPrompt,"systemPrompt": systemPrompt
        },
        this.ctxManager.cloneContext(),
        __options__.tb?.__tb(),
        __clientRegistry__,
        __collector__,
        __options__.tags || {},
        __env__,
        __signal__,
        __options__.watchers,
      )
      return __raw__.parsed(false) as types.AgentResponse
    } catch (error: any) {
      throw toBamlError(error);
    }
  }
  
  SummarizeCoderContext(
      systemPrompt: string,context: types.CoderContext,
      __baml_options__?: BamlCallOptions<never>
  ): types.CoderContext {
    try {
      const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
      const __signal__ = __options__.signal;

      if (__signal__?.aborted) {
        throw new BamlAbortError('Operation was aborted', __signal__.reason);
      }

      // Check if onTick is provided and reject for sync operations
      if (__options__.onTick) {
        throw new Error("onTick is not supported for synchronous functions. Please use the async client instead.");
      }

      const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector : [__options__.collector]) : [];
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __options__.clientRegistry;
      if (__options__.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__options__.client);
      }

      const __raw__ = this.runtime.callFunctionSync(
        "SummarizeCoderContext",
        {
          "systemPrompt": systemPrompt,"context": context
        },
        this.ctxManager.cloneContext(),
        __options__.tb?.__tb(),
        __clientRegistry__,
        __collector__,
        __options__.tags || {},
        __env__,
        __signal__,
        __options__.watchers,
      )
      return __raw__.parsed(false) as types.CoderContext
    } catch (error: any) {
      throw toBamlError(error);
    }
  }
  
  SummarizeContext(
      systemPrompt: string,context: types.Message[],
      __baml_options__?: BamlCallOptions<never>
  ): types.Message[] {
    try {
      const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
      const __signal__ = __options__.signal;

      if (__signal__?.aborted) {
        throw new BamlAbortError('Operation was aborted', __signal__.reason);
      }

      // Check if onTick is provided and reject for sync operations
      if (__options__.onTick) {
        throw new Error("onTick is not supported for synchronous functions. Please use the async client instead.");
      }

      const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector : [__options__.collector]) : [];
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __options__.clientRegistry;
      if (__options__.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__options__.client);
      }

      const __raw__ = this.runtime.callFunctionSync(
        "SummarizeContext",
        {
          "systemPrompt": systemPrompt,"context": context
        },
        this.ctxManager.cloneContext(),
        __options__.tb?.__tb(),
        __clientRegistry__,
        __collector__,
        __options__.tags || {},
        __env__,
        __signal__,
        __options__.watchers,
      )
      return __raw__.parsed(false) as types.Message[]
    } catch (error: any) {
      throw toBamlError(error);
    }
  }
  
  SummarizeDebuggerContext(
      systemPrompt: string,context: types.DebuggerContext,
      __baml_options__?: BamlCallOptions<never>
  ): types.DebuggerContext {
    try {
      const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
      const __signal__ = __options__.signal;

      if (__signal__?.aborted) {
        throw new BamlAbortError('Operation was aborted', __signal__.reason);
      }

      // Check if onTick is provided and reject for sync operations
      if (__options__.onTick) {
        throw new Error("onTick is not supported for synchronous functions. Please use the async client instead.");
      }

      const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector : [__options__.collector]) : [];
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __options__.clientRegistry;
      if (__options__.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__options__.client);
      }

      const __raw__ = this.runtime.callFunctionSync(
        "SummarizeDebuggerContext",
        {
          "systemPrompt": systemPrompt,"context": context
        },
        this.ctxManager.cloneContext(),
        __options__.tb?.__tb(),
        __clientRegistry__,
        __collector__,
        __options__.tags || {},
        __env__,
        __signal__,
        __options__.watchers,
      )
      return __raw__.parsed(false) as types.DebuggerContext
    } catch (error: any) {
      throw toBamlError(error);
    }
  }
  
  SummarizeEpisodic(
      systemPrompt: string,episodicMem: types.EpisodicMemory,
      __baml_options__?: BamlCallOptions<never>
  ): string {
    try {
      const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
      const __signal__ = __options__.signal;

      if (__signal__?.aborted) {
        throw new BamlAbortError('Operation was aborted', __signal__.reason);
      }

      // Check if onTick is provided and reject for sync operations
      if (__options__.onTick) {
        throw new Error("onTick is not supported for synchronous functions. Please use the async client instead.");
      }

      const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector : [__options__.collector]) : [];
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __options__.clientRegistry;
      if (__options__.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__options__.client);
      }

      const __raw__ = this.runtime.callFunctionSync(
        "SummarizeEpisodic",
        {
          "systemPrompt": systemPrompt,"episodicMem": episodicMem
        },
        this.ctxManager.cloneContext(),
        __options__.tb?.__tb(),
        __clientRegistry__,
        __collector__,
        __options__.tags || {},
        __env__,
        __signal__,
        __options__.watchers,
      )
      return __raw__.parsed(false) as string
    } catch (error: any) {
      throw toBamlError(error);
    }
  }
  
  TesterAgent(
      userPrompt: string,systemPrompt: string,
      __baml_options__?: BamlCallOptions<never>
  ): types.TesterResponse {
    try {
      const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
      const __signal__ = __options__.signal;

      if (__signal__?.aborted) {
        throw new BamlAbortError('Operation was aborted', __signal__.reason);
      }

      // Check if onTick is provided and reject for sync operations
      if (__options__.onTick) {
        throw new Error("onTick is not supported for synchronous functions. Please use the async client instead.");
      }

      const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector : [__options__.collector]) : [];
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __options__.clientRegistry;
      if (__options__.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__options__.client);
      }

      const __raw__ = this.runtime.callFunctionSync(
        "TesterAgent",
        {
          "userPrompt": userPrompt,"systemPrompt": systemPrompt
        },
        this.ctxManager.cloneContext(),
        __options__.tb?.__tb(),
        __clientRegistry__,
        __collector__,
        __options__.tags || {},
        __env__,
        __signal__,
        __options__.watchers,
      )
      return __raw__.parsed(false) as types.TesterResponse
    } catch (error: any) {
      throw toBamlError(error);
    }
  }
  
  UIExpertAgent(
      
      __baml_options__?: BamlCallOptions<events.UIExpertAgentEventCollector>
  ): string {
    try {
      const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
      const __signal__ = __options__.signal;

      if (__signal__?.aborted) {
        throw new BamlAbortError('Operation was aborted', __signal__.reason);
      }

      // Check if onTick is provided and reject for sync operations
      if (__options__.onTick) {
        throw new Error("onTick is not supported for synchronous functions. Please use the async client instead.");
      }

      const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector : [__options__.collector]) : [];
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __options__.clientRegistry;
      if (__options__.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__options__.client);
      }

      const __raw__ = this.runtime.callFunctionSync(
        "UIExpertAgent",
        {
          
        },
        this.ctxManager.cloneContext(),
        __options__.tb?.__tb(),
        __clientRegistry__,
        __collector__,
        __options__.tags || {},
        __env__,
        __signal__,
        __options__.watchers,
      )
      return __raw__.parsed(false) as string
    } catch (error: any) {
      throw toBamlError(error);
    }
  }
  
}

export const b = new BamlSyncClient(DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME, DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_CTX)