/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import { FieldType } from '@boundaryml/baml/native'
import { TypeBuilder as _TypeBuilder, EnumBuilder, EnumViewer, ClassBuilder, ClassViewer } from '@boundaryml/baml/type_builder'
import { DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME } from "./globals"

export { FieldType, EnumBuilder, ClassBuilder }

export default class TypeBuilder {
    private tb: _TypeBuilder;
    
    Abort: ClassViewer<'Abort', "action" | "reason">;
    
    AgentContext: ClassViewer<'AgentContext'>;
    
    AgentResponse: ClassViewer<'AgentResponse'>;
    
    AgentSummary: ClassViewer<'AgentSummary', "title" | "summary">;
    
    Apify: ClassViewer<'Apify', "action" | "urls" | "maxPages">;
    
    ApifyRes: ClassViewer<'ApifyRes', "status" | "itemcount" | "scrapeRes">;
    
    BraveRes: ClassViewer<'BraveRes', "type" | "result">;
    
    BraveResult: ClassViewer<'BraveResult', "title" | "url" | "description" | "pageAge">;
    
    CoderContext: ClassViewer<'CoderContext', "task" | "dependentSummary" | "repoTree" | "skills" | "recentTurns">;
    
    CoderSession: ClassViewer<'CoderSession', "taskId" | "role" | "status" | "iterationCount" | "timestamp" | "content">;
    
    ComplexityVerdict: ClassViewer<'ComplexityVerdict', "complex">;
    
    Context7: ClassViewer<'Context7', "action" | "library" | "query">;
    
    DebuggerContext: ClassViewer<'DebuggerContext', "repoTree" | "originalError" | "fixHistory" | "skills" | "recentTurns">;
    
    DebuggerSession: ClassViewer<'DebuggerSession', "taskId" | "role" | "status" | "iterationCount" | "timestamp" | "content" | "rawTranscript">;
    
    DebuggingDone: ClassViewer<'DebuggingDone', "action" | "editedFile" | "errors">;
    
    Decision: ClassViewer<'Decision', "actor" | "decision" | "accepted">;
    
    DeleteFile: ClassViewer<'DeleteFile', "action" | "path">;
    
    Design: ClassViewer<'Design', "taskId" | "summary">;
    
    DesignVariants: ClassViewer<'DesignVariants', "prompts">;
    
    DocsSearch: ClassViewer<'DocsSearch', "type" | "library" | "query">;
    
    Done: ClassViewer<'Done', "action" | "filesEdited">;
    
    EditFile: ClassViewer<'EditFile', "action" | "path" | "edits">;
    
    EpisodicMemory: ClassViewer<'EpisodicMemory', "sessionGoal" | "userRequests" | "impFacts" | "decisions" | "toolResults" | "generatedArtifacts" | "openTasks" | "preferences" | "entities" | "summary">;
    
    Error: ClassViewer<'Error', "fileName" | "error" | "source" | "taskId">;
    
    ErrorResponse: ClassViewer<'ErrorResponse', "error" | "file" | "line">;
    
    FetchDocs: ClassViewer<'FetchDocs', "action" | "query" | "library">;
    
    FileEdit: ClassViewer<'FileEdit', "fileName" | "summary">;
    
    FileEditOp: ClassViewer<'FileEditOp', "oldString" | "newString">;
    
    Fixes: ClassViewer<'Fixes', "error" | "fixSummary">;
    
    GetSkill: ClassViewer<'GetSkill', "action" | "skillName">;
    
    ItemRes: ClassViewer<'ItemRes', "title" | "description" | "url">;
    
    Message: ClassViewer<'Message', "role" | "content" | "timestamp">;
    
    PlannerTodo: ClassViewer<'PlannerTodo', "id" | "task" | "agent" | "status" | "dependency" | "designNeeded">;
    
    Question: ClassViewer<'Question', "question" | "option">;
    
    ReadFile: ClassViewer<'ReadFile', "action" | "path">;
    
    Research: ClassViewer<'Research', "action" | "searchType">;
    
    ResearcherContext: ClassViewer<'ResearcherContext', "query" | "skills">;
    
    ResearcherResponse: ClassViewer<'ResearcherResponse', "query" | "result">;
    
    ResearcherSession: ClassViewer<'ResearcherSession', "taskId" | "role" | "status" | "iterationCount" | "timestamp" | "content">;
    
    RunCommand: ClassViewer<'RunCommand', "action" | "command" | "cwd">;
    
    SessionMap: ClassViewer<'SessionMap', "coder" | "debuggerr" | "tester" | "researcher" | "uiExpert">;
    
    Skill: ClassViewer<'Skill', "name" | "description" | "content">;
    
    StitchTool: ClassViewer<'StitchTool', "action" | "prompt" | "userId">;
    
    SubAgentsContexts: ClassViewer<'SubAgentsContexts', "coder" | "debuggerr" | "tester" | "researcher" | "uiExpert">;
    
    TaskComplexity: ClassViewer<'TaskComplexity', "complexity" | "POA">;
    
    TaskSummary: ClassViewer<'TaskSummary', "taskId" | "summary">;
    
    Tavily: ClassViewer<'Tavily', "action" | "query" | "maxResults">;
    
    TesterContext: ClassViewer<'TesterContext', "skills">;
    
    TesterResponse: ClassViewer<'TesterResponse'>;
    
    TesterSession: ClassViewer<'TesterSession', "taskId" | "role" | "status" | "iterationCount" | "timestamp" | "content">;
    
    ToolResult: ClassViewer<'ToolResult', "success" | "content">;
    
    UIExpertContext: ClassViewer<'UIExpertContext', "userPrompt" | "priorDesigns" | "skills">;
    
    UIExpertSession: ClassViewer<'UIExpertSession', "taskId" | "role" | "status" | "iterationCount" | "timestamp" | "content">;
    
    WebScrape: ClassViewer<'WebScrape', "type" | "urls" | "maxPages">;
    
    WebSearch: ClassViewer<'WebSearch', "type" | "query" | "maxResults">;
    
    WriteFile: ClassViewer<'WriteFile', "action" | "path" | "content">;
    
    
    Agent: EnumViewer<'Agent', "CoderAgent" | "DebuggerAgent" | "TesterAgent" | "UIExpertAgent" | "ResearcherAgent">;
    
    ContextType: EnumViewer<'ContextType', "CoderContext" | "DebuggerContext" | "TesterContext" | "UIExpertContext" | "ResearcherContext">;
    

    constructor() {
        this.tb = new _TypeBuilder({
          classes: new Set([
            "Abort","AgentContext","AgentResponse","AgentSummary","Apify","ApifyRes","BraveRes","BraveResult","CoderContext","CoderSession","ComplexityVerdict","Context7","DebuggerContext","DebuggerSession","DebuggingDone","Decision","DeleteFile","Design","DesignVariants","DocsSearch","Done","EditFile","EpisodicMemory","Error","ErrorResponse","FetchDocs","FileEdit","FileEditOp","Fixes","GetSkill","ItemRes","Message","PlannerTodo","Question","ReadFile","Research","ResearcherContext","ResearcherResponse","ResearcherSession","RunCommand","SessionMap","Skill","StitchTool","SubAgentsContexts","TaskComplexity","TaskSummary","Tavily","TesterContext","TesterResponse","TesterSession","ToolResult","UIExpertContext","UIExpertSession","WebScrape","WebSearch","WriteFile",
          ]),
          enums: new Set([
            "Agent","ContextType",
          ]),
          runtime: DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME
        });
        
        this.Abort = this.tb.classViewer("Abort", [
          "action","reason",
        ]);
        
        this.AgentContext = this.tb.classViewer("AgentContext", [
          
        ]);
        
        this.AgentResponse = this.tb.classViewer("AgentResponse", [
          
        ]);
        
        this.AgentSummary = this.tb.classViewer("AgentSummary", [
          "title","summary",
        ]);
        
        this.Apify = this.tb.classViewer("Apify", [
          "action","urls","maxPages",
        ]);
        
        this.ApifyRes = this.tb.classViewer("ApifyRes", [
          "status","itemcount","scrapeRes",
        ]);
        
        this.BraveRes = this.tb.classViewer("BraveRes", [
          "type","result",
        ]);
        
        this.BraveResult = this.tb.classViewer("BraveResult", [
          "title","url","description","pageAge",
        ]);
        
        this.CoderContext = this.tb.classViewer("CoderContext", [
          "task","dependentSummary","repoTree","skills","recentTurns",
        ]);
        
        this.CoderSession = this.tb.classViewer("CoderSession", [
          "taskId","role","status","iterationCount","timestamp","content",
        ]);
        
        this.ComplexityVerdict = this.tb.classViewer("ComplexityVerdict", [
          "complex",
        ]);
        
        this.Context7 = this.tb.classViewer("Context7", [
          "action","library","query",
        ]);
        
        this.DebuggerContext = this.tb.classViewer("DebuggerContext", [
          "repoTree","originalError","fixHistory","skills","recentTurns",
        ]);
        
        this.DebuggerSession = this.tb.classViewer("DebuggerSession", [
          "taskId","role","status","iterationCount","timestamp","content","rawTranscript",
        ]);
        
        this.DebuggingDone = this.tb.classViewer("DebuggingDone", [
          "action","editedFile","errors",
        ]);
        
        this.Decision = this.tb.classViewer("Decision", [
          "actor","decision","accepted",
        ]);
        
        this.DeleteFile = this.tb.classViewer("DeleteFile", [
          "action","path",
        ]);
        
        this.Design = this.tb.classViewer("Design", [
          "taskId","summary",
        ]);
        
        this.DesignVariants = this.tb.classViewer("DesignVariants", [
          "prompts",
        ]);
        
        this.DocsSearch = this.tb.classViewer("DocsSearch", [
          "type","library","query",
        ]);
        
        this.Done = this.tb.classViewer("Done", [
          "action","filesEdited",
        ]);
        
        this.EditFile = this.tb.classViewer("EditFile", [
          "action","path","edits",
        ]);
        
        this.EpisodicMemory = this.tb.classViewer("EpisodicMemory", [
          "sessionGoal","userRequests","impFacts","decisions","toolResults","generatedArtifacts","openTasks","preferences","entities","summary",
        ]);
        
        this.Error = this.tb.classViewer("Error", [
          "fileName","error","source","taskId",
        ]);
        
        this.ErrorResponse = this.tb.classViewer("ErrorResponse", [
          "error","file","line",
        ]);
        
        this.FetchDocs = this.tb.classViewer("FetchDocs", [
          "action","query","library",
        ]);
        
        this.FileEdit = this.tb.classViewer("FileEdit", [
          "fileName","summary",
        ]);
        
        this.FileEditOp = this.tb.classViewer("FileEditOp", [
          "oldString","newString",
        ]);
        
        this.Fixes = this.tb.classViewer("Fixes", [
          "error","fixSummary",
        ]);
        
        this.GetSkill = this.tb.classViewer("GetSkill", [
          "action","skillName",
        ]);
        
        this.ItemRes = this.tb.classViewer("ItemRes", [
          "title","description","url",
        ]);
        
        this.Message = this.tb.classViewer("Message", [
          "role","content","timestamp",
        ]);
        
        this.PlannerTodo = this.tb.classViewer("PlannerTodo", [
          "id","task","agent","status","dependency","designNeeded",
        ]);
        
        this.Question = this.tb.classViewer("Question", [
          "question","option",
        ]);
        
        this.ReadFile = this.tb.classViewer("ReadFile", [
          "action","path",
        ]);
        
        this.Research = this.tb.classViewer("Research", [
          "action","searchType",
        ]);
        
        this.ResearcherContext = this.tb.classViewer("ResearcherContext", [
          "query","skills",
        ]);
        
        this.ResearcherResponse = this.tb.classViewer("ResearcherResponse", [
          "query","result",
        ]);
        
        this.ResearcherSession = this.tb.classViewer("ResearcherSession", [
          "taskId","role","status","iterationCount","timestamp","content",
        ]);
        
        this.RunCommand = this.tb.classViewer("RunCommand", [
          "action","command","cwd",
        ]);
        
        this.SessionMap = this.tb.classViewer("SessionMap", [
          "coder","debuggerr","tester","researcher","uiExpert",
        ]);
        
        this.Skill = this.tb.classViewer("Skill", [
          "name","description","content",
        ]);
        
        this.StitchTool = this.tb.classViewer("StitchTool", [
          "action","prompt","userId",
        ]);
        
        this.SubAgentsContexts = this.tb.classViewer("SubAgentsContexts", [
          "coder","debuggerr","tester","researcher","uiExpert",
        ]);
        
        this.TaskComplexity = this.tb.classViewer("TaskComplexity", [
          "complexity","POA",
        ]);
        
        this.TaskSummary = this.tb.classViewer("TaskSummary", [
          "taskId","summary",
        ]);
        
        this.Tavily = this.tb.classViewer("Tavily", [
          "action","query","maxResults",
        ]);
        
        this.TesterContext = this.tb.classViewer("TesterContext", [
          "skills",
        ]);
        
        this.TesterResponse = this.tb.classViewer("TesterResponse", [
          
        ]);
        
        this.TesterSession = this.tb.classViewer("TesterSession", [
          "taskId","role","status","iterationCount","timestamp","content",
        ]);
        
        this.ToolResult = this.tb.classViewer("ToolResult", [
          "success","content",
        ]);
        
        this.UIExpertContext = this.tb.classViewer("UIExpertContext", [
          "userPrompt","priorDesigns","skills",
        ]);
        
        this.UIExpertSession = this.tb.classViewer("UIExpertSession", [
          "taskId","role","status","iterationCount","timestamp","content",
        ]);
        
        this.WebScrape = this.tb.classViewer("WebScrape", [
          "type","urls","maxPages",
        ]);
        
        this.WebSearch = this.tb.classViewer("WebSearch", [
          "type","query","maxResults",
        ]);
        
        this.WriteFile = this.tb.classViewer("WriteFile", [
          "action","path","content",
        ]);
        
        
        this.Agent = this.tb.enumViewer("Agent", [
          "CoderAgent","DebuggerAgent","TesterAgent","UIExpertAgent","ResearcherAgent",
        ]);
        
        this.ContextType = this.tb.enumViewer("ContextType", [
          "CoderContext","DebuggerContext","TesterContext","UIExpertContext","ResearcherContext",
        ]);
        
    }

    reset(): void {
        this.tb.reset();
        // TODO: This should happen in Rust. Problem is, when we construct the
        // typebuilder we instantiate class builders once and it seems to make
        // a JS copy, bypassing the Rust side? In Python however, every time we
        // access a class builder with @property, we get a new instance that
        // wraps over the Rust type builder, so we only need to call tb.reset().
        // In JS it's not possible unless we refactor the way class builders are
        // accessed.
        
    }

    __tb() {
      return this.tb._tb();
    }

    string(): FieldType {
        return this.tb.string()
    }

    literalString(value: string): FieldType {
        return this.tb.literalString(value)
    }

    literalInt(value: number): FieldType {
        return this.tb.literalInt(value)
    }

    literalBool(value: boolean): FieldType {
        return this.tb.literalBool(value)
    }

    int(): FieldType {
        return this.tb.int()
    }

    float(): FieldType {
        return this.tb.float()
    }

    bool(): FieldType {
        return this.tb.bool()
    }

    list(type: FieldType): FieldType {
        return this.tb.list(type)
    }

    null(): FieldType {
        return this.tb.null()
    }

    map(key: FieldType, value: FieldType): FieldType {
        return this.tb.map(key, value)
    }

    union(types: FieldType[]): FieldType {
        return this.tb.union(types)
    }

    addClass<Name extends string>(name: Name): ClassBuilder<Name> {
        return this.tb.addClass(name);
    }

    addEnum<Name extends string>(name: Name): EnumBuilder<Name> {
        return this.tb.addEnum(name);
    }

    addBaml(baml: string): void {
        this.tb.addBaml(baml);
    }
}