/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
/**
 * Recursively partial type that can be null.
 *
 * @deprecated Use types from the `partial_types` namespace instead, which provides type-safe partial implementations
 * @template T The type to make recursively partial.
 */
export type RecursivePartialNull<T> = T extends object
    ? { [P in keyof T]?: RecursivePartialNull<T[P]> }
    : T | null;

export interface Checked<T,CheckName extends string = string> {
    value: T,
    checks: Record<CheckName, Check>,
}

export interface Check {
    name: string,
    expr: string
    status: "succeeded" | "failed"
}

export function all_succeeded<CheckName extends string>(checks: Record<CheckName, Check>): boolean {
    return get_checks(checks).every(check => check.status === "succeeded")
}

export function get_checks<CheckName extends string>(checks: Record<CheckName, Check>): Check[] {
    return Object.values(checks)
}
export enum Agent {
  CoderAgent = "CoderAgent",
  DebuggerAgent = "DebuggerAgent",
  TesterAgent = "TesterAgent",
  UIExpertAgent = "UIExpertAgent",
  ResearcherAgent = "ResearcherAgent",
}

export enum ContextType {
  CoderContext = "CoderContext",
  DebuggerContext = "DebuggerContext",
  TesterContext = "TesterContext",
  UIExpertContext = "UIExpertContext",
  ResearcherContext = "ResearcherContext",
}

export enum ToolType {
  Apify = "Apify",
  Context7 = "Context7",
  Tavily = "Tavily",
  Stitch = "Stitch",
  ReadFile = "ReadFile",
  WriteFile = "WriteFile",
  EditFile = "EditFile",
  RunCommand = "RunCommand",
  DeleteFile = "DeleteFile",
  QnA = "QnA",
}

export interface AgentContext {
  
}

export interface AgentResponse {
  
}

export interface Apify {
  urls: string[]
  maxPages: number
  
}

export interface ApifyRes {
  status: string
  itemcount: number
  scrapeRes: ItemRes[]
  
}

export interface BraveRes {
  type: string
  result: BraveResult[]
  
}

export interface BraveResult {
  title: string
  url: string
  description: string
  pageAge: string
  
}

export interface CoderContext {
  dependentSummary: TaskSummary[]
  repoTree: string
  
}

export interface ComplexityLevel {
  complex: boolean
  qnaNeeded: boolean
  
}

export interface Context7 {
  library: string
  query: string
  
}

export interface DebuggerContext {
  originalError: string
  fixHistory: Fixes[]
  
}

export interface DebuggingDone {
  action: "done"
  editedFile: FileEdit[]
  errors: Record<string, string>
  
}

export interface Decision {
  actor: string
  decision: string
  accepted: string
  
}

export interface DeleteFile {
  action: "delete"
  path: string
  
}

export interface Design {
  taskId: number
  summary: string
  
}

export interface DocsSeach {
  type: "docsSearch"
  library: string
  query: string
  
}

export interface Done {
  action: "done"
  filesEdited: FileEdit[]
  
}

export interface EditFile {
  action: "edit"
  fileName: string
  content: string
  
}

export interface EpisodicMemory {
  sessionGoal: string
  userRequests: string[]
  impFacts: string[]
  decisions: string[]
  toolResults: string[]
  generatedArtifacts: string[]
  openTasks: string[]
  preferences: string[]
  entities: string[]
  summary: string
  
}

export interface Error {
  fileName: string
  error: string
  
}

export interface ErrorResponse {
  error: string
  file: string
  line: number
  
}

export interface FetchDocs {
  action: "fetchDocs"
  query: string
  library: string
  
}

export interface FileEdit {
  fileName: string
  summary: string
  
}

export interface FinalResponse {
  status: "success" | "failed"
  previewUrl?: string | null
  deployUrl?: string | null
  
}

export interface Fixes {
  error: string
  fixSummary: string
  
}

export interface ItemRes {
  title: string
  description: string
  url: string
  
}

export interface LLMResponse {
  stopReason: "completed" | "aborted" | "toolCall" | "QnA"
  content: string
  toolCall?: ToolCall | null
  questions?: Question[] | null
  
}

export interface Message {
  role: "user" | "assistant" | "toolCall" | "system"
  content: string
  timestamp: string
  
}

export interface PlannerTodo {
  id: number
  task: string
  agent: "coder" | "debuggerr" | "tester" | "researcher" | "uiExpert"
  status: "pending" | "completed"
  dependency: number[]
  
}

export interface Question {
  question: string
  option: string[]
  
}

export interface ReadFile {
  action: "read"
  path: string
  
}

export interface Research {
  action: "research"
  searchType: WebSearch | WebScrape | DocsSeach
  
}

export interface ResearcherContext {
  query: string
  
}

export interface ResearcherResponse {
  query: string
  result: BraveRes | ApifyRes
  
}

export interface RunCommand {
  action: "runCommand"
  command: string
  
}

export interface StitchTool {
  prompt: string
  userId: string
  
}

export interface SubAgentsContexts {
  coder: CoderContext
  debuggerr: DebuggerContext
  tester: TesterContext
  researcher: ResearcherContext
  uiExpert: UIExpertContext
  
}

export interface TaskComplexity {
  complexity: boolean
  POA: PlannerTodo[] | string
  
}

export interface TaskSummary {
  taskId: string
  summary: string
  
}

export interface Tavily {
  query: string
  maxResults: number
  
}

export interface TesterContext {
  
}

export interface TesterResponse {
  
}

export interface ToolCall {
  type: ToolType
  apify?: Apify | null
  context7?: Context7 | null
  tavily?: Tavily | null
  stitch?: StitchTool | null
  readFile?: ReadFile | null
  writeFile?: WriteFile | null
  editFile?: EditFile | null
  runCommand?: RunCommand | null
  deleteFile?: DeleteFile | null
  
}

export interface ToolResult {
  success: boolean
  content?: FileEdit[] | null
  
}

export interface UIExpertContext {
  userPrompt: string
  priorDesigns: Design[]
  
}

export interface WebScrape {
  type: "webScrape"
  urls: string[]
  maxPages: number
  
}

export interface WebSearch {
  type: "webSearch"
  query: string
  maxResults: number
  
}

export interface WriteFile {
  action: "writeFile"
  path: string
  content: string
  
}

export type SubAgentsContext = CoderContext | DebuggerContext | TesterContext | ResearcherContext | UIExpertContext
