/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
/**
 * Recursively partial type that can be null.
 *
 * @deprecated Use types from the `partial_types` namespace instead, which provides type-safe partial implementations
 * @template T The type to make recursively partial.
 */
export type RecursivePartialNull<T> = T extends object
    ? { [P in keyof T]?: RecursivePartialNull<T[P]> }
    : T | null;

export interface Checked<T,CheckName extends string = string> {
    value: T,
    checks: Record<CheckName, Check>,
}

export interface Check {
    name: string,
    expr: string
    status: "succeeded" | "failed"
}

export function all_succeeded<CheckName extends string>(checks: Record<CheckName, Check>): boolean {
    return get_checks(checks).every(check => check.status === "succeeded")
}

export function get_checks<CheckName extends string>(checks: Record<CheckName, Check>): Check[] {
    return Object.values(checks)
}
export enum Skill {
  WebSearch = "WebSearch",
  Read_blog = "Read_blog",
  Read_docs = "Read_docs",
  Read_file = "Read_file",
  Write_file = "Write_file",
  Edit_file = "Edit_file",
  Bash = "Bash",
  Pytest = "Pytest",
  Jest = "Jest",
  Read_codebase = "Read_codebase",
}

export interface AgentResponse {
  
}

export interface ApifyRes {
  status: string
  itemcount: number
  scrapeRes: ItemRes[]
  
}

export interface BraveRes {
  type: string
  result: BraveResult[]
  
}

export interface BraveResult {
  title: string
  url: string
  description: string
  pageAge: string
  
}

export interface CoderContext {
  type: "writeFile" | "readFile" | "commandResult" | "infoResult" | "research"
  content: string
  
}

export interface DebuggerResponse {
  status: string
  editedFile: FileEdit[]
  errors: Record<string, string>
  
}

export interface DeleteFile {
  action: "delete"
  path: string
  
}

export interface Done {
  action: "done"
  filesEdited: FileEdit[]
  
}

export interface Error {
  fileName: string
  error: string
  
}

export interface Errors {
  
}

export interface FetchDocs {
  action: "fetchDocs"
  query: string
  library: string
  
}

export interface FileEdit {
  fileName: string
  summary: string
  
}

export interface FinalResponse {
  status: "success" | "failed"
  previewUrl?: string | null
  deployUrl?: string | null
  
}

export interface ItemRes {
  title: string
  description: string
  url: string
  
}

export interface Message {
  
}

export interface Option {
  text: string
  
}

export interface Question {
  question: string
  option: Option[]
  
}

export interface ReadFile {
  action: "read"
  path: string
  
}

export interface Research {
  action: "research"
  query: string
  
}

export interface ResearcherResponse {
  query: string
  result: BraveRes | ApifyRes
  
}

export interface Resume {
  name: string
  email: string
  experience: string[]
  skills: string[]
  
}

export interface RunCommand {
  action: "runCommand"
  command: string
  
}

export interface SubAgent {
  name: string
  skills: Skill[]
  
}

export interface Task {
  id: string
  objective: string
  agent: string
  depends_upon: string[]
  
}

export interface TesterResponse {
  
}

export interface WriteFile {
  action: "writeFile"
  path: string
  content: string
  
}
